# Workflow name
name: Validate PRs

on:
  # Event for the workflow to run on
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook
      - name: Run unit test
        run: npm run test
      - uses: Eun/http-server-action@v1
        with:
          directory: ${{ github.workspace }}/storybook-static
          port: 6006
          no-cache: false
          index-files: |
            ["index.html", "index.htm"]
          allowed-methods: |
            ["GET", "HEAD"]
          log: 'log.txt'
          logTime: 'true'
      - name: Test http server
        run: |
          curl -vvvv http://localhost:6006/index.html
          cat log.txt
      - name: Run tests
        run: npm run test-storybook
